// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using logindemo.Data;

#nullable disable

namespace logindemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250910100057_Allincluded")]
    partial class Allincluded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("logindemo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PoliceStationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("logindemo.Models.PoliceStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PoliceStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001001",
                            StationName = "FOOD CELL PS KARAIKAL"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001002",
                            StationName = "KOTTUCHERRY"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001003",
                            StationName = "TOWN"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001004",
                            StationName = "NEDUNGADU"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001005",
                            StationName = "NERAVY"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001006",
                            StationName = "THIRUNALLAR"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001007",
                            StationName = "T.R.PATTINAM"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001008",
                            StationName = "WOMEN PS"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001009",
                            StationName = "PCR CELL PS KARAIKAL"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001010",
                            StationName = "TRAFFIC NORTH"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001011",
                            StationName = "EXCISE PS KARAIKAL"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001012",
                            StationName = "COASTAL PS KARAIKAL"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26001013",
                            StationName = "TRAFFIC SOUTH"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002001",
                            StationName = "VAC PS (VIGILANCE & ANTI CORRUPTION)"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002002",
                            StationName = "CID PS"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002003",
                            StationName = "DHANVANTRI NAGAR (D. NAGAR)"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002004",
                            StationName = "REDDIARPALAYAM"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002005",
                            StationName = "MUDALIARPET"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002006",
                            StationName = "METTUPALAYAM"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002007",
                            StationName = "VILLIANUR"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002008",
                            StationName = "WOMEN PS VILLIANOUR"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002009",
                            StationName = "MANGALAM"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002010",
                            StationName = "FOOD CELL PS PUDUCHERRY"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002011",
                            StationName = "MAHE PS"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002012",
                            StationName = "PALLOOR PS"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002013",
                            StationName = "YANAM PS"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002014",
                            StationName = "PCR CELL PS PUDUCHERRY"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002015",
                            StationName = "PCR CELL PS YANAM"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002016",
                            StationName = "GRAND BAZAR"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002017",
                            StationName = "KALAPET"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002018",
                            StationName = "MUTHIALPET"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002019",
                            StationName = "LAWSPET"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002020",
                            StationName = "ODIANSALAI"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002021",
                            StationName = "ORLEANPET"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002022",
                            StationName = "WOMEN PS"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002023",
                            StationName = "TRAFFIC EAST"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002024",
                            StationName = "TRAFFIC WEST"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002025",
                            StationName = "ARIANKUPPAM"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002026",
                            StationName = "SEDARAPET"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002027",
                            StationName = "BAHOUR"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002028",
                            StationName = "KIRUMAMPAKKAM"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002029",
                            StationName = "KATTERIKUPPAM"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002030",
                            StationName = "NETTAPAKKAM"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002031",
                            StationName = "THAVALAKUPPAM"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002032",
                            StationName = "THIRUBUVANAI"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002033",
                            StationName = "THIRUKANUR"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002034",
                            StationName = "EXCISE PS MAHE"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002035",
                            StationName = "EXCISE PS YANAM"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002036",
                            StationName = "TRAFFIC SOUTH"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002037",
                            StationName = "EXCISE PS PUDUCHERRY"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002038",
                            StationName = "COASTAL PS PUDUCHERRY"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002039",
                            StationName = "COASTAL PS MAHE"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002040",
                            StationName = "COASTAL PS YANAM"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002041",
                            StationName = "TRAFFIC NORTH"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002042",
                            StationName = "PS ECONOMIC OFFENSES WING"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002043",
                            StationName = "PS CYBER CRIME CELL"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2025, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "",
                            StationCode = "26002044",
                            StationName = "TRAFFIC YANAM POLICE STATION"
                        });
                });

            modelBuilder.Entity("logindemo.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalDocuments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PoliceStationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PoliceStationId")
                        .HasColumnType("int");

                    b.Property<string>("PoliceStationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PoliceStationId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("logindemo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("logindemo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("logindemo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("logindemo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("logindemo.Models.Ticket", b =>
                {
                    b.HasOne("logindemo.Models.PoliceStation", "PoliceStationEntity")
                        .WithMany("Tickets")
                        .HasForeignKey("PoliceStationId");

                    b.Navigation("PoliceStationEntity");
                });

            modelBuilder.Entity("logindemo.Models.PoliceStation", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
